// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vijhxdtxvbxoheijgrwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpamh4ZHR4dmJ4b2hlaWpncnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MTgxOTQsImV4cCI6MjA4NjM5NDE5NH0.Clk9kdq80Ph1-rsS6g6D30mAuRJknnFVpj5F8mK4qpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});